import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type ReportData = {
  id: string;
  patient: string;
  date: string;
  status: "infected" | "uninfected";
  confidence: number;
  species: string;
};

export const generatePatientPDF = (report: ReportData) => {
  const doc = new jsPDF();
  const isInfected = report.status === "infected";

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("ParaDetect AI", 14, 18);
  doc.setFontSize(10);
  doc.text("Intelligent Malaria Detection & Diagnostic Report", 14, 26);
  doc.text(`Report ID: ${report.id}`, 14, 33);

  // Status banner
  doc.setFillColor(isInfected ? 239 : 34, isInfected ? 68 : 197, isInfected ? 68 : 94);
  doc.rect(0, 44, 210, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text(isInfected ? "⚠ MALARIA DETECTED" : "✓ NO MALARIA DETECTED", 14, 53);

  // Patient info table
  doc.setTextColor(0, 0, 0);
  autoTable(doc, {
    startY: 65,
    head: [["Field", "Details"]],
    body: [
      ["Report ID", report.id],
      ["Patient", report.patient],
      ["Date", report.date],
      ["Diagnosis", isInfected ? "Malaria Infected" : "Uninfected / Clear"],
      ["AI Confidence", `${report.confidence}%`],
      ["Parasite Species", report.species],
    ],
    theme: "striped",
    headStyles: { fillColor: [15, 118, 110] },
  });

  // Analysis notes
  const finalY = (doc as any).lastAutoTable?.finalY ?? 140;
  doc.setFontSize(12);
  doc.setTextColor(51, 51, 51);
  doc.text("Analysis Notes", 14, finalY + 14);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const note = isInfected
    ? "Plasmodium parasites were detected in the blood smear sample. The AI model identified characteristic ring-form trophozoites within red blood cells. Further clinical evaluation and confirmatory testing is recommended."
    : "No malaria parasites were detected in the blood smear sample. Red blood cells appear morphologically normal. If symptoms persist, a repeat test is recommended.";
  doc.text(doc.splitTextToSize(note, 180), 14, finalY + 22);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by ParaDetect AI — For clinical use, confirm with a certified pathologist.", 14, 280);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 285);

  doc.save(`${report.id}_diagnostic_report.pdf`);
};
